export default async function(page,R) {
  await page.getByText('New Character',{exact:true}).click();
  R.ok(await page.locator('#character-creator canvas').count()===1,'new character opens live creator');
  R.ok(await page.locator('#character-creator canvas').getAttribute('data-renderer')==='gameplay','creator uses shared gameplay pixel pipeline');
  R.ok(await page.evaluate(()=>Number(document.querySelector('#character-creator canvas').dataset.texelDensity)===window.__game.pr.unitsPerPx),'preview preserves gameplay texel density');
  const root=page.locator('#character-creator');
  await root.locator('[data-key="frame"][data-value="tall"]').click();
  await root.locator('[data-key="skin"]').nth(5).click();
  await root.locator('[data-category="Hair"]').click();
  R.ok(await root.locator('[data-key="hair"]').count()===10,'ten selectable hairstyles');
  for(const b of await root.locator('[data-key="hair"]').all()) await b.click();
  await root.locator('[data-key="hair"][data-value="braided"]').click();
  await root.locator('[data-key="hairColor"]').nth(4).click();
  await root.locator('[data-category="Face"]').click();
  for(const key of ['face','eyes']) for(const b of await root.locator(`[data-key="${key}"]`).all()) await b.click();
  await root.locator('[data-category="Details"]').click();
  for(const key of ['beard','detail']) for(const b of await root.locator(`[data-key="${key}"]`).all()) await b.click();
  for(const camera of ['left','right','in','out']) await root.locator(`[data-camera="${camera}"]`).click();
  await root.locator('[data-category="Class"]').click();
  R.ok(await root.locator('[data-class="soulbound"]').count()===1,'Soulbound is available in new character class selection');
  for(const b of await root.locator('[data-class]').all()) await b.click();
  await root.locator('[data-class="archer"]').click();
  await root.locator('[data-category="Hair"]').click();
  R.ok(await root.locator('[data-value="braided"]').getAttribute('aria-pressed')==='true','appearance survives class switches');
  await root.locator('[data-category="Class"]').click();
  await root.locator('[data-class="soulbound"]').click();
  R.ok(await root.locator('.creator-class-label').textContent()==='Soulbound','Soulbound selection updates the in-game character preview');
  await root.locator('[data-category="Name"]').click();
  R.ok(await root.locator('[data-action="next"]').isDisabled(),'blank name cannot create save');
  await page.locator('#creator-name').fill('Willow');
  await root.locator('[data-action="random"]').click();
  R.ok(await page.locator('#creator-name').inputValue()==='Willow','randomise preserves name');
  await root.locator('[data-category="Class"]').click();
  R.ok(await root.locator('[data-class="soulbound"]').getAttribute('aria-pressed')==='true','randomise preserves Soulbound class');
  await root.locator('[data-category="Body"]').click();
  await root.locator('[data-value="tall"]').click();
  await root.locator('[data-category="Name"]').click();
  await page.evaluate(()=>{window.__game.story.opening=()=>{};});
  await root.locator('[data-action="next"]').click();
  await page.waitForFunction(()=>window.__game.profile?.name==='Willow'&&!document.getElementById('character-creator'));
  const saved=await page.evaluate(async()=>{const g=window.__game;await g.save();return JSON.stringify(g.inv.appearance);});
  R.ok(await page.evaluate(()=>window.__game.player.m.frame.scale.y===1.12),'frame applied to gameplay rig without animation scale collision');
  const gear=await page.evaluate(async()=>{const g=window.__game;const before=JSON.stringify(g.inv.appearance);g.player.m.setGear({...g.inv.equip,head:{base:'kabuto',r:2}});g.player.m.setGear(g.inv.equip);g.ui.openInventory();g.ui.doll.frame(.016);const same=JSON.stringify(g.inv.appearance)===before&&g.ui.doll.hero.frame.scale.y===1.12;g.ui.closeInventory();return same;});
  R.ok(gear,'equipment swap and inventory preview retain cosmetics');
  await page.reload();await page.waitForFunction(()=>window.__game&&!document.getElementById('loading'));
  await page.getByText('Willow · soulbound · Lv 1',{exact:true}).click();await page.waitForFunction(()=>window.__game.profile?.name==='Willow');
  R.ok(await page.evaluate(s=>JSON.stringify(window.__game.inv.appearance)===s,saved),'appearance survives actual save and reload');
  R.ok(await page.locator('#character-creator').count()===0,'continuing bypasses creator');
  await page.reload();await page.waitForFunction(()=>window.__game&&!document.getElementById('loading'));
  await page.getByText('New Character',{exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await page.locator('[data-category="Hair"]').click();
  await page.screenshot({path:'/tmp/creator-mobile-hair.png'});
  R.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile has no horizontal overflow');
  await page.locator('[data-action="back"]').click();
  R.ok(await page.locator('#character-creator').count()===0,'Back cancels without creating another profile');
  R.ok(await page.evaluate(()=>window.__game.saveProvider.loadCharacters().length===1),'cancelled draft does not create save');
}
