import {fresh,sim} from './lib.mjs';
export default async function(page,R){
 await fresh(page,'samurai',{level:16});
 await page.evaluate(()=>window.__game.ui.navigate('bag'));
 R.ok(await page.locator('#creative-inventory').count()===0,'creative catalogue absent outside devroom');
 R.ok(await page.evaluate(async()=>{const {grantCreative}=await import('./src/dev/creative.js');return grantCreative(window.__game,'gear:heavensdivide')===false;}),'spawn action also rejects outside-devroom calls');
 await page.evaluate(()=>{const g=window.__game;g.ui.navigate('resume');g.loadArea('devroom','spawn');g.ui.navigate('bag');});
 const search=page.getByRole('searchbox',{name:'Search every item'});
 R.ok(await search.isVisible(),'opening devroom inventory shows creative search');
 R.ok(await page.evaluate(async()=>{const {CREATIVE_ITEMS}=await import('./src/dev/creative.js');const I=window.__items;return [...I.WEAPONS,...I.ARMORS,...I.LEGENDARIES,...I.ACCESSORIES].every(x=>CREATIVE_ITEMS.some(c=>c.id==='gear:'+x.id))&&CREATIVE_ITEMS.every(x=>typeof x.name==='string');}),'catalogue covers every registered equipment base and named variant');
 await search.fill('heaven');await page.getByRole('button',{name:'Inspect Heaven’s Divide',exact:true}).click();await page.getByRole('button',{name:'Add Heaven’s Divide',exact:true}).click();
 R.ok(await page.evaluate(()=>window.__game.inv.bag.some(x=>x.unique==='heavensdivide'&&x.prismatic)),'searched prismatic weapon creates real usable item');
 await search.fill('hush shard');await page.getByRole('button',{name:'Inspect Hush Shard',exact:true}).click();await page.getByLabel('Spawn quantity',{exact:true}).selectOption('64');
 const before=await page.evaluate(()=>window.__game.inv.mats.shard||0);
 await page.getByRole('button',{name:'Add Hush Shard',exact:true}).click();
 R.ok(await page.evaluate(()=>window.__game.inv.mats.shard)===before+64,'stack quantity applies to materials');
 await search.fill('cinder rod');await page.getByRole('button',{name:'Inspect Cinder Rod',exact:true}).click();await page.getByRole('button',{name:'Add Cinder Rod',exact:true}).click();
 R.ok(await page.evaluate(()=>window.__game.inv.fireRod&&window.__game.inv.activeTool==='fireRod'),'tool entry grants functional tool');
 await search.fill('nothingmatches123');R.ok(await page.getByText('No items found').isVisible(),'empty search has clear feedback');
 await search.fill('');await page.getByLabel('Item category',{exact:true}).selectOption('Equipment');
 await page.getByLabel('Item rarity',{exact:true}).selectOption('Prismatic');
 R.ok(await page.locator('.creative-item').count()===4,'Prismatic filter isolates three signature weapons and Worldseed');
 await page.waitForFunction(()=>[...document.querySelectorAll('.creative-item img')].every(i=>i.complete&&i.naturalWidth>0));
 R.ok(await page.locator('.creative-item img').evaluateAll(imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0)),'all visible entries have loaded image icons');
 R.ok(await page.evaluate(async()=>{const {CREATIVE_ITEMS}=await import('./src/dev/creative.js');return CREATIVE_ITEMS.filter(x=>x.preview).every(x=>{const actual=window.__items.makeNamed(x.id.slice(5),1);return x.preview.r===actual.r&&!!x.preview.prismatic===!!actual.prismatic;});}),'rarity labels agree with every granted equipment variant');
 await page.getByRole('button',{name:'Inspect Heaven’s Divide',exact:true}).click();
 R.ok(await page.locator('.creative-add').evaluate(el=>{const p=document.querySelector('.inv-panel').getBoundingClientRect(),r=el.getBoundingClientRect();return r.bottom<=p.bottom&&r.top>=p.top;}),'Add button stays inside desktop viewport');
 await page.screenshot({path:'/tmp/mossling-creative-polished.jpg'});
 await page.getByRole('button',{name:'Reset filters',exact:true}).click();
 await search.fill('azure');await page.getByRole('button',{name:'Clear search',exact:true}).click();
 R.ok(await search.inputValue()==='','clear search restores results');
 await page.getByLabel('Item order',{exact:true}).selectOption('rarity');
 R.ok(await page.locator('.creative-item .creative-rarity').first().innerText()==='Prismatic','rarity sort places Prismatic first');
 await page.setViewportSize({width:390,height:844});
 R.ok(await page.evaluate(()=>{const p=document.querySelector('.inv-panel');return p.scrollWidth<=p.clientWidth+1;}),'creative catalogue has no horizontal overflow at 390px');
 await page.screenshot({path:'/tmp/mossling-creative-mobile.jpg'});
 await page.setViewportSize({width:1280,height:720});

 await page.getByRole('button',{name:'My bag',exact:true}).click();
 R.ok(await page.locator('#baggrid').isVisible(),'My bag restores regular equipment management');
 await page.evaluate(()=>{const g=window.__game;g.ui.navigate('resume');g.loadArea('overworld','village');g.ui.navigate('bag');});
 R.ok(await page.locator('#creative-inventory').count()===0&&await page.locator('#baggrid').isVisible(),'leaving devroom removes creative controls');
}
