import {sim, walkTo, mouseAt, talkThrough} from './lib.mjs';
import {mkdirSync} from 'node:fs';
const step=page=>page.evaluate(()=>window.__game.onboarding.step);
const at=async(page,x,z,facing=0)=>{await page.evaluate(([x,z,facing])=>{const g=window.__game;g.player.x=x+90;g.player.z=z+70;g.player.setState('move');g.player.facing=facing;g.snapCamera();},[x,z,facing]);await sim(page,2);};
export default async function(page,R){
 await page.evaluate(()=>window.__start(true,'samurai'));await sim(page,3);
 R.ok(await step(page)==='move','fresh arrival starts with movement');
 R.ok(await page.evaluate(()=>!window.__game.entities.some(e=>e.id==='intro')&&!window.__game.locked()),'no forced fight or cutscene at spawn');
 mkdirSync('docs/screens/hub-arrival',{recursive:true});
 await page.screenshot({path:'docs/screens/hub-arrival/spawn-desktop.png'});
 R.ok(await walkTo(page,148.5,135.5,120,.3),'spawn path reaches village square');
 R.ok(await step(page)==='welcome','actual walking completes movement lesson');
 R.ok(await walkTo(page,157.5,136,180,.3),'square path reaches Brisk');
 await page.evaluate(()=>{const g=window.__game;g.story.talk(g.entities.find(e=>e.id==='brisk'));});await talkThrough(page);await sim(page,3);
 R.ok(await step(page)==='attack','Brisk advances to training');
 await at(page,71,66);await mouseAt(page,161,134.5);await sim(page,1,['KeyC']);await sim(page,30);
 R.ok(await step(page)==='roll','real attack hits target');
 await page.evaluate(()=>{const g=window.__game;g.onboarding.warning=null;g.onboarding.sweepT=0;});await sim(page,34);
 await sim(page,1,['Space','KeyD']);await sim(page,18,['KeyD']);await sim(page,36);
 R.ok(await step(page)==='heal','real roll clears telegraphed practice sweep');
 const pots=await page.evaluate(()=>window.__game.inv.potions);
 await sim(page,1,['KeyH']);await sim(page,30);
 R.ok(await step(page)==='loot'&&await page.evaluate(()=>window.__game.inv.potions)===pots,'tonic lesson refunds its practice potion');
 await at(page,69,67.5);await sim(page,1,['KeyF']);await sim(page,3);
 R.ok(await step(page)==='equip','actual interaction opens welcome supplies');
 await sim(page,1,['KeyE']);await sim(page,2);
 R.ok(await page.locator('#baggrid .welcome-kit').count()===1,'welcome armour is highlighted in inventory');
 const paused=await page.evaluate(()=>{const g=window.__game,x=g.player.x,z=g.player.z;window.__sim(60,['KeyD']);return g.player.x===x&&g.player.z===z;});
 // The engine may advance its clock, but inventory must stop enemies and lesson sweeps.
 R.ok(paused&&await page.evaluate(()=>window.__game.ui.invOpen),'inventory pauses world movement');
 await page.evaluate(()=>{const g=window.__game;g.equipItem(g.inv.bag.findIndex(i=>i.welcomeGift));g.ui.closeInventory();});await sim(page,2);
 R.ok(await step(page)==='ability','equipping the welcome armour advances lesson');
 await at(page,71,66);await mouseAt(page,161,134.5);await sim(page,1,['Digit1']);await sim(page,30);
 R.ok(await step(page)==='rest','real class ability advances lesson');
 await page.evaluate(()=>window.__game.save());await page.reload();await page.waitForFunction(()=>window.__game&&!document.getElementById('loading'));await page.evaluate(()=>window.__start(false));await sim(page,3);
 R.ok(await step(page)==='rest'&&await page.evaluate(()=>!window.__game.entities.some(e=>e.id==='intro')),'save and reload preserve peaceful training progress');
 await at(page,56.5,61.4,Math.PI);await sim(page,1,['KeyF']);await sim(page,3);
 R.ok(await step(page)==='ready','Bellstone interaction completes resting lesson');
 await at(page,69,67.5);const gifts=await page.evaluate(()=>{const g=window.__game;return g.inv.bag.length;});
 await page.evaluate(()=>window.__game.entities.find(e=>e.constructor.name==='WelcomeChest').interact());await talkThrough(page);
 R.ok(await page.evaluate(()=>window.__game.inv.bag.length)===gifts,'welcome chest cannot duplicate rewards after reload');
 await at(page,68,66.5);await page.screenshot({path:'docs/screens/hub-arrival/yard-desktop.png'});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'docs/screens/hub-arrival/yard-mobile.png'});
 R.ok(await page.evaluate(()=>{const r=document.getElementById('guide').getBoundingClientRect();return r.x>=0&&r.right<=innerWidth&&r.y>=0&&r.bottom<=innerHeight;}),'mobile lesson card fits viewport');
 await page.setViewportSize({width:1280,height:720});
 await page.evaluate(()=>{const g=window.__game;g.story.talk(g.entities.find(e=>e.id==='brisk'));});await talkThrough(page);await sim(page,35);
 R.ok(await page.evaluate(()=>window.__game.flags.onboarding.phase==='complete'&&window.__game.entities.some(e=>e.id==='intro'&&e.waves.length===1)),'explicit ready choice starts a short first fight');
 await page.evaluate(()=>{const g=window.__game;g.flags.introFought=true;g.entities.filter(e=>e.arena||e.id==='intro').forEach(e=>e.remove());g.onboarding.begin(true);g.onboarding.skip();g.onboarding.finish();});await sim(page,2);
 R.ok(await page.evaluate(()=>!window.__game.onboarding.active&&!window.__game.entities.some(e=>e.id==='intro')),'replay and skip finish without another opening battle');
}
