import { fresh, sim } from './lib.mjs';
export default async function(page,R){
  await fresh(page,'witch',{level:12});
  await page.evaluate(()=>{const g=window.__game;g.inv.sp=20;g.flags.guideDone=true;g.guide.render();g.inv.coins=1500;for(let i=0;i<18;i++)g.inv.bag.push(window.__items.genItem({level:12,cls:'witch',rarity:i%5}));for(const slot of ['helm','armor','arms','legs','boots','charm'])g.inv.equip[slot]=window.__items.genItem({level:12,cls:'witch',slot,rarity:3});g.recalc();g.inv.hp=g.inv.maxHp;g.ui.updateHud();g.render(0);});
  const shot=async name=>{await page.screenshot({path:`docs/screens/pass7/${name}.jpg`});};
  await shot('hud');
  await page.keyboard.press('e');await page.waitForFunction(()=>window.__game.ui.invOpen);
  R.ok(await page.locator('.bag-heading').isVisible(),'E opens real inventory');
  R.ok(await page.locator('.slotbox').count()===9,'nine actual equipment slots');
  const before=await page.evaluate(()=>({hp:window.__game.inv.hp,x:window.__game.player.x,z:window.__game.player.z}));
  await sim(page,5,['KeyW','KeyC']);
  R.ok(await page.evaluate(b=>{const g=window.__game;return g.player.x===b.x&&g.player.z===b.z&&g.inv.hp===b.hp},before),'menu blocks movement and combat');
  await shot('inventory');
  await page.getByLabel('Search inventory').fill('zzzzzzz');
  R.ok(await page.locator('#baggrid .cell:not([data-i="-99"])').count()===0,'search filters bag');
  await page.getByLabel('Search inventory').fill('');
  await page.locator('#baggrid .cell:not([data-i="-99"])').first().click();
  await page.locator('[data-act="favourite"]').click();
  R.ok(await page.locator('[data-act="salvage"]').isDisabled(),'protected gear cannot be salvaged');
  await page.locator('[data-act="favourite"]').click();
  await page.locator('[data-act="equip"]').click();
  R.ok(await page.evaluate(()=>!!window.__game.lastEquip),'equip updates actual gear');
  await page.locator('.journal-tabs:visible [data-page="skills"]').click();
  R.ok(await page.locator('.tree').isVisible(),'inventory to skill tree');
  await page.locator('.tn[data-id="kindling"]').click();
  await page.locator('[data-act="learn"]').click();
  R.ok(await page.evaluate(()=>window.__game.inv.tree.kindling===1),'learn node through real skill UI');
  await page.locator('.tn[data-id="nova"]').click();
  await page.locator('[data-assign="5"]').click();
  R.ok(await page.evaluate(()=>window.__game.inv.loadout[5]==='nova'),'assign ability to sixth socket');
  await shot('skills');
  await page.locator('.journal-tabs:visible [data-page="map"]').click();
  R.ok(await page.locator('#bigmap').isVisible(),'skills to map');await shot('map');
  await page.locator('.journal-tabs:visible [data-page="quests"]').click();
  await page.getByRole('button',{name:'Track this entry',exact:true}).click();
  R.ok(await page.getByRole('button',{name:'Tracking this entry',exact:true}).isVisible(),'quest tracking');await shot('journal');
  await page.locator('.journal-tabs:visible [data-page="gear"]').click();await shot('codex');
  await page.locator('.journal-tabs:visible [data-page="settings"]').click();await shot('settings');
  for(const category of ['Audio','Gameplay','Controls','Interface']){await page.locator(`[data-category="${category}"]`).click();R.ok(await page.locator('.settings-options').isVisible(),`${category} settings reachable`);}
  await page.getByLabel('Quest tracker',{exact:true}).selectOption('1');
  R.ok(await page.evaluate(()=>window.__game.settings.questGuide===false),'quest tracker setting wired');
  await page.getByLabel('Reduced UI motion',{exact:true}).selectOption('1');
  R.ok(await page.evaluate(()=>document.documentElement.classList.contains('reduce-motion')),'reduced motion applied');
  await page.locator('.journal-tabs:visible [data-page="resume"]').click();
  await page.keyboard.press('m');await page.waitForFunction(()=>!document.getElementById('pause').classList.contains('hidden'));
  R.ok(await page.locator('#bigmap').isVisible(),'M opens map without muting music');
  await page.keyboard.press('k');await page.waitForFunction(()=>window.__game.ui.invOpen&&window.__game.ui.invTab==='skills');R.ok(true,'K opens skills without guard');
  await page.keyboard.press('e');await page.waitForFunction(()=>window.__game.ui.invTab==='bag');R.ok(true,'E returns from skills to inventory');
  await page.keyboard.press('Escape');await page.waitForFunction(()=>!window.__game.ui.invOpen);
  await page.evaluate(()=>{const g=window.__game;g.inv.hp=g.inv.maxHp*.25;g.inv.potions=3;g.player.state='move';});
  await sim(page,1,['KeyH']);await sim(page,25);
  R.ok(await page.evaluate(()=>window.__game.inv.potions===2),'H drinks tonic',JSON.stringify(await page.evaluate(()=>({potions:window.__game.inv.potions,state:window.__game.player.state,inventory:window.__game.ui.invOpen,pause:!document.getElementById('pause').classList.contains('hidden')}))));
  await page.evaluate(()=>{const g=window.__game;Object.assign(g.inv.mats,{shard:100,thornheart:5,echo:5,ember:5});g.inv.recipes.push('emberseeds');g.ui.openCraft();});
  await shot('crafting');
  await page.locator('[data-m="reinforce"]').click();await shot('reinforcement');
  await page.locator('#cr-go').click();R.ok(await page.evaluate(()=>window.__game.inv.equip.weapon.upgradeLevel>0),'reinforce uses real transaction');
  await page.locator('#craft .service-close').click();
  await page.evaluate(()=>{const g=window.__game;g.discoveredBellstones=['overworld:village','dungeon:entrance'];const stone=g.entities.find(e=>e.constructor.name==='Bellstone');g.player.x=stone.x+.8;g.player.z=stone.z;g.player.combatT=0;stone.interact();});
  await page.waitForFunction(()=>window.__game.ui.talking);await sim(page,100);
  await shot('bellstone');
  await page.keyboard.press('Escape');await page.waitForFunction(()=>!window.__game.ui.talking);
  await page.evaluate(()=>{const g=window.__game;const npc=g.entities.find(e=>e.id==='posy'||e.npc==='posy');if(npc)g.story.talk(npc);else g.ui.say('Posy','Bring your essences to the workbench.');});
  await sim(page,100);await shot('dialogue');
  await page.evaluate(()=>{const u=window.__game.ui;u.dialogQ=[];u.typing=null;u.choice=null;u.dialogCb=null;u.show('dialog',false);window.__game.story.shop();});
  await shot('shop');
  const coins=await page.evaluate(()=>window.__game.inv.coins);
  await page.locator('#shop-list button:not(:disabled)').first().click();
  R.ok(await page.evaluate(c=>window.__game.inv.coins<c,coins),'shop mouse Buy uses live purchase');
  await page.evaluate(()=>{window.__game.ui.show('shop',false);});
  // The real developer facility, no test profile modification persisted.
  await page.evaluate(()=>{window.__dev.execute('/sandbox on');window.__dev.open();});await shot('developer');
  await page.evaluate(()=>{window.__dev.close();const g=window.__game;g.ui.dialogQ=[];g.ui.typing=null;g.ui.choice=null;g.ui.dialogCb=null;g.ui.show('dialog',false);g.cutscene=false;});
  for(const [w,h] of [[1280,720],[1600,900],[1920,1080],[2560,1080],[390,844]]){
    await page.setViewportSize({width:w,height:h});await page.evaluate(()=>window.__game.ui.navigate('bag'));
    const bounds=await page.locator('.inv-panel').boundingBox();R.ok(bounds.x>=0&&bounds.x+bounds.width<=w+1&&bounds.y>=0&&bounds.y+bounds.height<=h+1,`inventory contained ${w}x${h}`);
    await shot(`inventory-${w}`);
    await page.evaluate(()=>window.__game.ui.navigate('settings'));
    const sb=await page.locator('#pause>.panel').boundingBox();R.ok(sb.x>=0&&sb.x+sb.width<=w+1&&sb.y>=0&&sb.y+sb.height<=h+1,`settings contained ${w}x${h}`);
  }
}
