import { PreviewState, CLASSES, CATEGORIES, SLOT_LABELS, bagCapacity } from './state.js';
import { itemIconURL } from '../../src/preview.js';
import { HeroPortrait } from '../../src/hero_portrait.js';
import { compactHtml, detailsHtml, itemInfo, compareHtml, rarityOf, esc } from '../../src/item_info.js';
import { RARITY } from '../../src/rpg/items.js';
import { normalizeAppearance } from '../../src/appearance.js';
const $=id=>document.getElementById(id),state=new PreviewState();
const portrait=new HeroPortrait();portrait.mount($('doll-host'));
const appearance=normalizeAppearance({hair:'tousled',hairColor:'#28201e',skin:'#e5b18b'});
$('rarity').insertAdjacentHTML('beforeend',RARITY.map((r,i)=>`<option value="${i}">${r.name}</option>`).join(''));
$('class-select').innerHTML=Object.entries(CLASSES).map(([id,c])=>`<option value="${id}">${c.name}</option>`).join('');$('class-select').value=state.inv.cls;
const icon=it=>`<img src="${itemIconURL(it,state.inv.cls)}" alt="" draggable="false">`;
function itemButton(it,slot){const r=rarityOf(it),worn=state.equippedSlot(it),protectedItem=state.isProtected(it);return `<button class="item-slot ${state.selected===it?'selected':''}" style="--rarity:${r.color}" data-item="${esc(it.itemInstanceId)}" aria-pressed="${state.selected===it}" aria-label="${esc(it.name)}, ${r.name}${worn?', equipped':''}${protectedItem?', protected':''}" title="${esc(it.name)}">${icon(it)}<span class="slot-mark">${worn?'E':protectedItem?'◆':''}</span><span class="slot-label">${slot?SLOT_LABELS[slot]:r.name}</span>${protectedItem?'<span class="protected-mark" aria-hidden="true">◆</span>':''}</button>`;}
function renderBag(){const items=state.visible();$('capacity').textContent=`${state.inv.bag.length} / ${bagCapacity(state.inv)} slots`;$('categories').innerHTML=CATEGORIES.map(([id,name])=>`<button data-category="${id}" aria-pressed="${state.category===id}" class="${state.category===id?'active':''}">${name}</button>`).join('');
$('bag-grid').innerHTML=items.map(it=>itemButton(it)).join('')+(state.category==='all'&&state.rarity==='all'&&!state.query?Array.from({length:Math.max(0,bagCapacity(state.inv)-items.length)},()=>'<div class="empty-slot" aria-hidden="true"><span>·</span></div>').join(''):'');
$('empty').hidden=items.length>0;$('empty').textContent=state.inv.bag.length?'No matching equipment. Try another search or reset filters.':'Your sample satchel is empty.';$('result-count').textContent=`${items.length} shown · ${state.inv.lockedItems.length} protected`;}
function renderGear(){const render=slots=>slots.map(slot=>state.inv.equip[slot]?itemButton(state.inv.equip[slot],slot):`<div class="empty-equip"><span>◇</span><small>${SLOT_LABELS[slot]}</small></div>`).join('');$('equipment-left').innerHTML=render(['head','chest','arms','legs','boots']);$('equipment-right').innerHTML=render(['necklace','ring1','ring2','weapon']);
portrait.setGear(state.inv.cls,state.inv.equip,appearance);const s=state.stats,C=CLASSES[state.inv.cls];
$('character-stats').innerHTML=`<div class="vital"><span>Max health</span><b>${s.maxHp}</b><div class="health-track"></div></div><div class="vital"><span>Class resource</span><b style="color:${C.resColor}">${C.res}</b><small>${state.inv.cls==='soulbound'?'Up to 5 Echoes':'Combat resource'}</small></div><dl><div><dt>Weapon damage</dt><dd>${Math.round(s.wmin)}–${Math.round(s.wmax)}</dd></div><div><dt>Armour</dt><dd>${Math.round(s.armor)}</dd></div><div><dt>Critical chance</dt><dd>${s.crit.toFixed(1)}%</dd></div><div><dt>Move speed</dt><dd>${s.speed.toFixed(2)} tiles/s</dd></div></dl>`;}
function renderDetails(){const it=state.selected;$('details').disabled=!it;$('details').setAttribute('aria-expanded',String(state.expanded));$('details').textContent=state.expanded?'Less detail':'Details';if(!it){$('item-content').innerHTML='<p>Select equipment to inspect.</p>';$('equip').disabled=$('protect').disabled=true;return;}
const info=itemInfo(it,state.context);$('item-content').innerHTML=(state.expanded?detailsHtml:compactHtml)(it,state.context,icon(it))+(state.expanded?rollRanges(it):'')+compareHtml(it,state.current(it),state.context)+(info.weapon&&state.current(it)&&state.current(it)!==it?'<p class="ii-note">Speed multipliers use each weapon family’s base rate, not absolute attacks per second.</p>':'')+effectComparison(it)+(!state.equippedSlot(it)&&!info.own?`<p class="affinity-note">${esc(info.weapon?.scaling||'Equipment from another class.')}</p>`:'');
$('equip').disabled=$('protect').disabled=false;$('equip').textContent=state.equippedSlot(it)?'Unequip sample':'Equip sample';$('protect').textContent=state.isProtected(it)?'Unprotect':'Protect';$('protect').setAttribute('aria-pressed',String(state.isProtected(it)));}
function rollRanges(it){const rolls=(it.rolledAffixes||[]).filter(a=>Array.isArray(a.rollRange));return rolls.length?`<section class="roll-ranges"><h3>Rolled stat ranges</h3>${rolls.map(a=>`<p>${esc(a.name||a.id)} <b>${a.rollRange[0]}–${a.rollRange[1]}${esc(a.unit||'')}</b> <small>${esc(a.tierName)} roll quality</small></p>`).join('')}</section>`:'';}
function effectComparison(it){const cur=state.current(it);if(!cur||cur===it)return '';const a=itemInfo(it,state.context),b=itemInfo(cur,state.context),lines=x=>[...x.unique,...x.properties.filter(p=>p.kind==='effect').map(p=>p.text)],A=lines(a),B=lines(b);if(JSON.stringify(A)===JSON.stringify(B))return '';return `<details class="effect-differences"><summary>Compare special effects</summary><h5>This item</h5>${A.length?A.map(x=>`<p>${esc(x)}</p>`).join(''):'<p>No special effects.</p>'}<h5>Equipped · ${esc(cur.name)}</h5>${B.length?B.map(x=>`<p>${esc(x)}</p>`).join(''):'<p>No special effects.</p>'}</details>`;}
function render(){renderBag();renderGear();renderDetails();}
$('inventory-preview').addEventListener('click',e=>{const it=e.target.closest('[data-item]');if(it){state.select(it.dataset.item);$('notice').textContent='';renderBag();renderDetails(); // update equipped selection without rebuilding the rig
for(const b of document.querySelectorAll('.equipment [data-item]')){b.classList.toggle('selected',b.dataset.item===state.selected?.itemInstanceId);b.setAttribute('aria-pressed',String(b.dataset.item===state.selected?.itemInstanceId));}return;}
const cat=e.target.closest('[data-category]');if(cat){state.category=cat.dataset.category;renderBag();document.querySelector(`[data-category="${state.category}"]`).focus();}});
$('search').addEventListener('input',e=>{state.query=e.target.value;renderBag();});for(const key of ['rarity','sort'])$(key).addEventListener('change',e=>{state[key]=e.target.value;renderBag();});
$('reset-filters').onclick=()=>{state.resetFilters();$('search').value='';$('rarity').value='all';$('sort').value='rarity';renderBag();};
$('details').onclick=()=>{state.expanded=!state.expanded;renderDetails();};$('equip').onclick=()=>{const message=state.equip();render();$('notice').textContent=message;};$('protect').onclick=()=>{state.toggleProtection();render();$('notice').textContent=state.isProtected(state.selected)?'Protected in this preview.':'Protection removed.';};
$('class-select').onchange=e=>{state.switchClass(e.target.value);render();$('notice').textContent='Separate sample character loaded.';};
$('turn-left').onclick=()=>portrait.rotY-=.35;$('turn-right').onclick=()=>portrait.rotY+=.35;$('zoom').oninput=e=>portrait.setZoom(Number(e.target.value));
portrait.pixel.renderer.domElement.addEventListener('wheel',()=>$('zoom').value=portrait.zoom);portrait.pixel.renderer.domElement.addEventListener('dblclick',()=>$('zoom').value=portrait.zoom);
window.addEventListener('weapon-icons-ready',render);let last=performance.now(),frame;function tick(now){portrait.frame(document.hidden?0:(now-last)/1000);last=now;frame=requestAnimationFrame(tick);}render();frame=requestAnimationFrame(tick);
window.addEventListener('pagehide',()=>{cancelAnimationFrame(frame);portrait.dispose();},{once:true});
// Inspectable test seam contains only sample data and this portrait, never a live Game.
window.__inventoryPreview={state,portrait,render};
